feat: add owner to topic event data
StreamLayer/sl-tinode pull request #43
Opened 2022-10-10 00:40 UTC by WatchDG

2022-10-10 06:07 UTC, sky3d approved these changes

2022-10-10 06:09 UTC, BrRenat reviewed
что за файл? pbx/model_grpc.pb.go

2022-10-10 06:15 UTC, WatchDG commented
> что за файл? pbx/model_grpc.pb.go

кодогенерация клиентов

2022-10-10 06:24 UTC, BrRenat approved these changes

2022-10-10 06:42 UTC, BrRenat requested changes
wait fix in staging branch

2022-10-10 06:57 UTC, BrRenat approved these changes

2022-10-10 06:57 UTC, BrRenat commented
ready to go

2022-10-10 07:06 UTC, merged

2022-10-10 07:09 UTC, thuban-arrakis commented
:tada: This PR is included in version 0.23.0-rc.4 :tada:

The release is available on [GitHub release](https://github.com/StreamLayer/sl-tinode/releases/tag/v0.23.0-rc.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-16 06:14 UTC, thuban-arrakis commented
:tada: This PR is included in version 0.23.0 :tada:

The release is available on [GitHub release](https://github.com/StreamLayer/sl-tinode/releases/tag/v0.23.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-21 11:38 UTC, thuban-arrakis commented
:tada: This PR is included in version 0.23.0-dev.1 :tada:

The release is available on [GitHub release](https://github.com/StreamLayer/sl-tinode/releases/tag/v0.23.0-dev.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-01 07:50 UTC, thuban-arrakis commented
:tada: This PR is included in version 0.23.0-upgrade.1 :tada:

The release is available on [GitHub release](https://github.com/StreamLayer/sl-tinode/releases/tag/v0.23.0-upgrade.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-17 14:10 UTC, thuban-arrakis commented
:tada: This PR is included in version 0.23.0-debug.1 :tada:

The release is available on [GitHub release](https://github.com/StreamLayer/sl-tinode/releases/tag/v0.23.0-debug.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: